import blue_tshirts from "../assets/images/blue-t-shirt.jpg";

export const products = [
  {
    id: 1,
    name: "blue t-shirts",
    price: 30,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
    category: "tops",
    gender: "men's",
    color: "blue",
    image: blue_tshirts,
  },
  {
    id: 2,
    name: "green t-shirts",
    price: 35,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
    category: "tops",
    gender: "men's",
    color: "green",
    image: blue_tshirts,
  },
  {
    id: 3,
    name: "purple t-shirts",
    price: 25,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
    category: "tops",
    gender: "men's",
    color: "purple",
    image: blue_tshirts,
  },
  {
    id: 4,
    name: "red t-shirts",
    price: 20,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
    category: "tops",
    gender: "women's",
    color: "red",
    image: blue_tshirts,
  },
  {
    id: 5,
    name: "stripe t-shirts",
    price: 30,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
    category: "tops",
    gender: "women's",
    color: "black",
    image: blue_tshirts,
  },
  {
    id: 6,
    name: "mens jacket",
    price: 100,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
    category: "outer",
    gender: "men's",
    color: "black",
    image: blue_tshirts,
  },
  // {
  //   id: 1,
  //   name: "blue t-shirts",
  //   price: 30,
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
  //   category: "outer",
  //   gender: "men's",
  //   color: "blue",
  //   image: blue_tshirts,
  // },
  // {
  //   id: 1,
  //   name: "blue t-shirts",
  //   price: 30,
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
  //   category: "outer",
  //   gender: "men's",
  //   color: "blue",
  // },
  // {
  //   id: 1,
  //   name: "blue t-shirts",
  //   price: 30,
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
  //   category: "outer",
  //   gender: "men's",
  //   color: "blue",
  // },
  // {
  //   id: 1,
  //   name: "blue t-shirts",
  //   price: 30,
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
  //   category: "outer",
  //   gender: "men's",
  //   color: "blue",
  // },
  // {
  //   id: 1,
  //   name: "blue t-shirts",
  //   price: 30,
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio quidem libero, est vel quaerat totam.",
  //   category: "outer",
  //   gender: "men's",
  //   color: "blue",
  // },
];
